### ISSUE TITLE
Add `json-codecs`

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/registry#121]
```json
{
  "name": "json-codecs",
  "ref": "v1.0.0",
  "compiler": "0.15.7",
  "location": {
    "githubOwner": "jordanmartinez",
    "githubRepo": "purescript-json-codecs"
  }
}
```

**Comment by JordanMartinez** [comment]
For those curious as to what this is: https://github.com/JordanMartinez/purescript-json-codecs/tree/master

**Comment by JordanMartinez** [comment]
```json
{
  "name": "json-codecs",
  "ref": "v2.0.0",
  "compiler": "0.15.7"
}
```

**Comment by thomashoneyman** [comment]
@JordanMartinez Sorry, 0.15.7 is still not available. You can still use earlier versions (like 0.15.4).

**Comment by JordanMartinez** [comment]
@thomashoneyman I updated to `0.15.7` so I could derive the `Bi*` type classes for one of my types. I'd rather keep that change and just update whatever needs to be updated to `0.15.7`. AFAIK, `easy-purescript-nix` now has `0.15.7` in it, so what do I do here to update that?

**Comment by thomashoneyman** [comment]
You can clone the registry-dev repo, run `nix flake update`, and commit the result. Let me know if you're able to do that, and if not I can do it later.

**Comment by JordanMartinez** [comment]
Done.
