### ISSUE TITLE
Update `json-codecs`

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/registry#124]
{
  "name": "json-codecs",
  "ref": "v2.0.0",
  "compiler": "0.15.7"
}

**Comment by thomashoneyman** [comment]
{
"name": "json-codecs",
"ref": "v2.0.0",
"compiler": "0.15.4"
}

**Comment by JordanMartinez** [comment]
{
"name": "json-codecs",
"ref": "v3.0.0",
"compiler": "0.15.7"
}
