### ISSUE TITLE
Update react-basic-dom

### ISSUE THREAD

**Issue by mjrussell** [purescript/registry#152]
```json
{
  "name": "react-basic-dom",
  "ref": "v6.1.0",
  "compiler": "0.15.4"
}
```

**Comment by MonoidMusician** [comment]
Resubmitting (the API won't pick up edits to comments, sorry):
```
{
  "name": "react-basic-dom",
  "ref": "v6.1.0",
  "compiler": "0.15.4"
}
```

**Comment by MonoidMusician** [comment]
It was published but it wasn't uploaded to Pursuit, not sure why:
https://github.com/purescript/registry/actions/runs/3895406543/jobs/6650688194#step:9:654

**Comment by thomashoneyman** [comment]
Pursuit must have been briefly down — unfortunately there isn't an easy way to re-run Pursuit publishing only right now, but we can delete and reimport this package to publish the docs.

**Comment by mjrussell** [comment]
Thanks for catching my edit, I should have thought about that. Do you want me to do the removal and re-add @thomashoneyman?

**Comment by thomashoneyman** [comment]
@mjrussell You'll need a trustee to actually delete a package; I've done it for ya!

```json
{
  "name": "react-basic-dom",
  "ref": "v6.1.0",
  "compiler": "0.15.4"
}
```

**Comment by thomashoneyman** [comment]
Well, that's not great. I have no idea why we're seeing a 502 status from Pursuit for this package.

**Comment by andys8** [comment]
> Well, that's not great. I have no idea why we're seeing a 502 status from Pursuit for this package.

[`react-basic-dom`](https://pursuit.purescript.org/packages/purescript-react-basic-dom/6.0.0/docs/React.Basic.DOM) is rather large. It could be that we're starting to hit [nginx](https://github.com/purescript/pursuit/blob/master/deploy/nginx.conf) size limits or timeouts? Can we reproduce the error by publishing the old way?

**Comment by thomashoneyman** [comment]
We bumped it to avoid size limits in the past:
https://github.com/purescript/pursuit/pull/471

This could be the same issue, but I feel like that was an Entity Too Large status, not a bad gateway status. Don't totally remember though!

**Comment by andys8** [comment]
Interesting. My wild guess would go in direction of either nginx or a load balancer having a 30 or 60 second timeout as default configuration. Is that something we can rule out from timestamps in the logs?

**Comment by mjrussell** [comment]
Coming back to this after a while, any thoughts on how to move forward or try to get this updated?

**Comment by thomashoneyman** [comment]
The package is in the registry so that part is handled. For the docs on pursuit, you can always try publishing docs via pulp locally. We need to add a way to just retry docs for a package to the registry, by adjusting the “publish” workflow such that if the package exists but docs do not it retries it. Just haven’t implemented it yet!

**Comment by thomashoneyman** [comment]
We can also introduce a retry for pursuit in case we get a spurious error — more details in this comment:

https://github.com/purescript/registry/issues/270#issuecomment-1550536611

**Comment by nsaunders** [comment]
I haven't tested this yet, but as a temporary workaround I created a GitHub Actions workflow to publish the Tecron docs to Pursuit when the registry workflow fails. https://github.com/nsaunders/purescript-tecton/blob/master/.github/workflows/pursuit.yml

**Comment by thomashoneyman** [comment]
Once these two PRs land, we'll have retries in the publishing pipeline for Pursuit documentation and will allow you to republish a package version (if it is missing docs) to retry docs generation manually.

https://github.com/purescript/registry-dev/pull/603
https://github.com/purescript/registry-dev/pull/604

**Comment by thomashoneyman** [comment]
Gonna give this a quick retry...

```json
{
  "name": "react-basic-dom",
  "ref": "v6.1.0",
  "compiler": "0.15.4"
}
```

**Comment by thomashoneyman** [comment]
Hm — persistent, repeated 502 error. I'll have to come back to this tomorrow, but at least we know that it's not just a lack of retries.

**Comment by thomashoneyman** [comment]
```json
{
  "name": "react-basic-dom",
  "ref": "v6.1.0",
  "compiler": "0.15.4"
}
```

**Comment by thomashoneyman** [comment]
Whew — finally, these docs are uploaded.
https://pursuit.purescript.org/packages/purescript-react-basic-dom/6.1.0

**Comment by mjrussell** [comment]
Thank you!
