### ISSUE TITLE
Remove jelly-hooks

### ISSUE THREAD

**Issue by f-f** [purescript/registry#197]
```json
{
  "packages": {
    "jelly-hooks": null
  }
}
```

**Comment by yukikurage** [comment]
Um,  `jelly-signal` needs to be set to 0.4.0 at the same time...

**Comment by f-f** [comment]
```
{
  "packages": {
    "jelly-hooks": null,
    "jelly-signal": "0.4.0"
  }
}
```

**Comment by yukikurage** [comment]
I have seen the same mirroring error before, but have no idea what it is.

Anyway, the package-set seems to be working fine now. Thank you very much.

(Also, moving modules from package to package is bad practice, right? I'll be careful in the future...)

**Comment by thomashoneyman** [comment]
The mirroring error is because the legacy package-sets repo supports only one package set per day, so if we release multiple here only the first one will be mirrored.
