### ISSUE TITLE
Update my-library

### ISSUE THREAD

**Issue by sumew** [purescript/registry#238]
```json
{
  "name": "purescript-geojson",
  "ref": "v0.0.2",
  "compiler": "0.15.7"
}
```

**Comment by f-f** [comment]
@sumew packages in the registry do not contain the `purescript-` prefix.

**Comment by sumew** [comment]
{
  "name": "geojson",
  "ref": "v0.0.2",
  "compiler": "0.15.7"
}

**Comment by thomashoneyman** [comment]
@sumew it looks like your update was correct; however, the registry automatically looks for and publishes packages when it notices they have published new semver git tags. That happens on a daily basis; so long as your package has no issues, it will be auto-imported every day.

**Comment by sumew** [comment]
@thomashoneyman The readme didn't make that clear. I'll create a PR with added info for the Readme.

**Comment by thomashoneyman** [comment]
The pertinent line is in the second paragraph, but I'll admit it's not obvious:

> As of September 2022, no package manager officially supports the registry. To register your package, please open an issue using the [Publish](https://github.com/purescript/registry#publish-a-package) workflow. Once registered, your package will be added to the package sets automatically (if it compiles with the current package set), its docs will be uploaded to Pursuit, and **any SemVer tag you publish on the repository in the future will automatically update your package in the registry.**

(emphasis added)
