### ISSUE TITLE
Update bolson

### ISSUE THREAD

**Issue by mikesol** [purescript/registry#247]
```json
{
  "name": "bolson",
  "ref": "v0.3.2",
  "compiler": "0.15.8"
}
```

**Comment by thomashoneyman** [comment]
Ugh, this is from a recent change and it looks like the path is being concatenated twice. I can fix it and get this in.

**Comment by mikesol** [comment]
Thanks! If it's not too much trouble, could you add `deku@v0.9.19` and `ocarina@v1.5.3` as well? Along with `bolson@v0.3.2`, they all depend on each other to make a new feature work. Thanks & lemme know.

**Comment by thomashoneyman** [comment]
Ah, OK, well this one's already uploaded.
