### ISSUE TITLE
Missing GitHub repositories

### ISSUE THREAD

**Issue by nsaunders** [purescript/registry#264]
Today I stumbled across the following packages which reference nonexistent repositories:
* https://github.com/purescript/registry/blob/main/metadata/chosen.json
* https://github.com/purescript/registry/blob/main/metadata/chosen-halogen.json

I'm not sure if there's a process to remove deleted libraries from the registry, but perhaps a trustee would want to take care of these if possible?

**Comment by f-f** [comment]
There are a whole bunch of packages that were in the Bower registry and that we couldn't import for some reason, but still chose to keep their name reserved so no one else could register those. This is why we keep a metadata file with no versions published.

However, soon we'll rework the legacy import of packages to just drop all packages published before 0.13. This will free up most (if not all) of these packages. We are tracking this effort in https://github.com/purescript/registry-dev/issues/577, so refer there for updates on this.
