### ISSUE TITLE
Add purescript-halogen-css-frameworks

### ISSUE THREAD

**Issue by deemp** [purescript/registry#285]
```json
{
  "name": "purescript-halogen-css-frameworks",
  "ref": "v1.0.0",
  "compiler": "0.15.9",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}
```

**Comment by deemp** [comment]
{
  "name": "halogen-css-frameworks",
  "ref": "v1.0.0",
  "compiler": "0.15.9",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}

**Comment by deemp** [comment]
```json
{
  "name": "purescript-halogen-css-frameworks",
  "ref": "v1.0.1",
  "compiler": "0.15.9",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}
```

**Comment by deemp** [comment]
{
  "name": "halogen-css-frameworks",
  "ref": "v1.0.0",
  "compiler": "0.15.9",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}

**Comment by thomashoneyman** [comment]
Hey @deemp — if you retry this with the 0.15.8 compiler it should be fine. We haven’t added support for 0.15.9 yet but will do that later today.

**Comment by deemp** [comment]
```json
{
  "name": "purescript-halogen-css-frameworks",
  "ref": "v1.0.0",
  "compiler": "0.15.8",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}
```

**Comment by deemp** [comment]
```json
{
  "name": "halogen-css-frameworks",
  "ref": "v1.0.0",
  "compiler": "0.15.8",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}
```

**Comment by deemp** [comment]
@thomashoneyman, should I trigger the build again?

**Comment by thomashoneyman** [comment]
```json
{
  "name": "halogen-css-frameworks",
  "ref": "v1.0.0",
  "compiler": "0.15.8",
  "location": {
    "githubOwner": "deemp",
    "githubRepo": "purescript-halogen-css-frameworks"
  }
}
```

Something is up with Pursuit publishing for libraries with large docs, unfortunately, but let's see if a retry works...

**Comment by deemp** [comment]
@thomashoneyman  nope, it didnt :(

**Comment by thomashoneyman** [comment]
@deemp Luckily your package _is_ in the registry, and in the package sets (see: https://github.com/purescript/registry/blob/d31cbdc432bba78a812431b0fc58c042c073e9fe/package-sets/24.5.0.json#L160), it's just that the documentation isn't uploaded to Pursuit. If you wish you can still attempt to do this manually using Pulp + Bower. I'm going to have to get to the root of the Pursuit issue sometime, as it also affects react-basic.

**Comment by nsaunders** [comment]
@deemp I have the same problem with [Tecton](https://github.com/nsaunders/purescript-tecton) also. Retrying manually with Bower and Pulp as @thomashoneyman suggested has worked for me. However, to avoid cluttering my environment with redundant build tools, I've also created a temporary [GitHub Actions workflow](https://github.com/nsaunders/purescript-tecton/blob/master/.github/workflows/pursuit.yml) that attempts to publish the docs to Pursuit, including retries. Though untested, it "should" work. The only special requirement is that you do need to create a Personal Access Token (PAT) and add it as a repo secret `GH_ACCESS_TOKEN`. Feel free to copy the workflow and give it a try for yourself... And if you do, please let me know if you encounter any errors. (Again, I haven't had an opportunity to test with a new Tecton version yet.)

**Comment by thomashoneyman** [comment]
@nsaunders It's strange because as far as I can tell the registry is doing the same thing that Pulp is doing, and so I don't know why there is a 502 error for some packages. It's not very informative from Pursuit's side 😆

**Comment by deemp** [comment]
@nsaunders, @thomashoneyman, I ran the script, and it didn't provide any output. Nor is the package available on Pursuit.

**Comment by nsaunders** [comment]
@deemp apologies, the YAML structure on that last step was incorrect: I forgot to nest the options under "with". That would likely explain the lack of any output.

Thanks for giving it a try and reporting back. I've fixed the options accordingly. If you would like to make the change on your side and try again, please let me know what happens!

**Comment by deemp** [comment]
@thomashoneyman, I decided to abstract from `Halogen` (https://github.com/deemp/purescript-css-frameworks/issues/2) and renamed the package to `css-frameworks`. 

I'll try to remove `halogen-css-frameworks` from the package set.__

**Comment by deemp** [comment]
{
  "packages": {
    "halogen-css-frameworks": null
  }
}

**Comment by f-f** [comment]
```
{
  "packages": {
    "halogen-css-frameworks": null
  }
}
```
