### ISSUE TITLE
Update react-icons

### ISSUE THREAD

**Issue by andys8** [purescript/registry#299]
```json
{
  "name": "react-icons",
  "ref": "v1.1.3",
  "compiler": "0.15.8"
}
```

**Comment by andys8** [comment]
Okay..

Published docs via `pulp publish` which worked.

```text
pulp publish
Checking your package is registered in purescript/registry... ok
Publishing purescript-react-icons at v1.1.3. Is this ok? [y/n] y
* About to execute:
> git push origin HEAD refs/tags/v1.1.3
Ok? [y/n] y
Everything up-to-date
* Uploading documentation to Pursuit...
* Done.
* You can view your package's documentation at: https://pursuit.purescript.org/packages/purescript-react-icons/1.1.3
```

**Comment by MonoidMusician** [comment]
Fabrizio's talking about the limit we set for package source uploads to the registry itself:
https://github.com/purescript/registry-dev/blob/30e00032cd98b3cdc9d6632f8608f9cb63fc583a/lib/src/Operation/Validation.purs#L110-L116

https://github.com/purescript/registry-dev/blob/30e00032cd98b3cdc9d6632f8608f9cb63fc583a/app/src/App/API.purs#L609-L615

**Comment by andys8** [comment]
The error message complains about `413` from pursuit though.

**Comment by f-f** [comment]
I was referring to 

> WARNING: Package tarball is 395725.0bytes, which exceeds the warning threshold of 200000.0 bytes.

The Pursuit problem is well known and we don't quite know what to do with it, so it's likely to be dealt with after the Registry is properly deployed and we rework the whole idea of Pursuit.

**Comment by thomashoneyman** [comment]
The warning is just so we can check on an abnormally large package to see if it’s OK (we allow packages up to 2mb). In this case looks like it’s just a large generated package. In other cases we’ve seen that we were inadvertently packaging enormous unnecessary files like benchmarking graphs, so that’s why we have the warning there.
