### ISSUE TITLE
Add missing classes to purescript-halogen-bootstrap5

### ISSUE THREAD

**Issue by tonicebrian** [purescript/registry#31]
{
"newPackageLocation": {
"githubOwner": "tonicebrian",
"githubRepo": "purescript-halogen-bootstrap5"
},
"newRef": "v2.1.0",
"packageName": "halogen-bootstrap5",
"buildPlan": { "compiler": "0.15.4" }
}

**Comment by thomashoneyman** [comment]
{
  "ref": "v2.1.0",
  "name": "halogen-bootstrap5",
  "compiler": "0.15.4"
}

**Comment by thomashoneyman** [comment]
@tonicebrian If you're publishing a new version of an existing package, then you don't _have_ to include the `location` field (it's stored from the previous publish of the package). Just as a note!

```jsonc
{
  "name": "halogen-bootstrap5",
  "ref": "v2.1.0",
  "compiler": "0.15.4"
}
```

**Comment by thomashoneyman** [comment]
Looks like this was automatically published last night:
https://github.com/purescript/registry/blob/8a8ffc91a2836379bac02b49aa57f2e42a9812a1/metadata/halogen-bootstrap5.json#L19-L24

**Comment by tonicebrian** [comment]
> Looks like this was automatically published last night:
> https://github.com/purescript/registry/blob/8a8ffc91a2836379bac02b49aa57f2e42a9812a1/metadata/halogen-bootstrap5.json#L19-L24

Does it mean that just pushing a tag to my repo publishes it?

**Comment by thomashoneyman** [comment]
Yes, once registered, we have an importer that runs each night to publish new versions. This will run for the duration of the alpha.
