### ISSUE TITLE
merge purescript/registry to purescript/package-sets

### ISSUE THREAD

**Issue by srghma** [purescript/registry#320]
it's so tedious

to add a new package to https://pursuit.purescript.org/ I have to:
- open pr to registry
- wait for merge
- open pr to package-sets
- wait for merge

expected:
- open pr to package-sets
- wait for merge

**Comment by thomashoneyman** [comment]
When the registry alpha launches (we’re working on it!) it’ll be the other way — you’ll add your package to the registry and it will automatically be added to the package sets if possible. Each time your package updates the updated version will also be added to the package sets.

**Comment by srghma** [comment]
ah, ok, super)

and how often new package-set will be published to pursuit?)

**Comment by thomashoneyman** [comment]
The goal is for Pursuit and package set publishing to both be done automatically. Every package version will be pushed to Pursuit. Packages eligible for the package set will be added or updated there. Conflicts will still have to be managed manually, like when a package update breaks another package in the set.

**Comment by f-f** [comment]
Tracking issues are #156, #272

**Comment by thomashoneyman** [comment]
I'm closing this since it's already being tracked. Thanks @srghma for bringing this up!
