### ISSUE TITLE
Add typelevel-regex

### ISSUE THREAD

**Issue by m-bock** [purescript/registry#394]
{
  "name": "typelevel-regex",
  "ref": "v0.0.1",
  "compiler": "0.15.10",
  "location": {
    "githubOwner": "thought2",
    "githubRepo": "purescript-typelevel-regex"
  }
}

**Comment by thought2** [comment]
{
"name": "typelevel-regex",
"ref": "v0.0.2",
"compiler": "0.15.10",
"location": {
"githubOwner": "thought2",
"githubRepo": "purescript-typelevel-regex"
}
}
