### ISSUE TITLE
SourceHut?

### ISSUE THREAD

**Issue by jgarte** [purescript/registry#40]
Hi, does the registry support SourceHut packages like this one?

https://git.sr.ht/~toastal/purescript-blurhash

**Comment by f-f** [comment]
We are planning this, but first need to disentangle other parts of the ecosystem from GitHub - mainly Pursuit, which assumes that every repo is on GitHub in many places.

This is tracked in https://github.com/purescript/registry-dev/issues/330 and https://github.com/purescript/registry-dev/pull/204

**Comment by jgarte** [comment]
Thanks for the links!
