### ISSUE TITLE
Update jelly

### ISSUE THREAD

**Issue by yukikurage** [purescript/registry#43]
```json
{
  "name": "jelly",
  "ref": "v0.7.0",
  "compiler": "0.15.4"
}
```

**Comment by yukikurage** [comment]
Uh, this is a mistake.
However, the Jelly metadata was updated 2 days ago, but the package-set does not seem to have been updated...

**Comment by thomashoneyman** [comment]
If it was missed, then you can submit a manual package set update:

https://github.com/purescript/registry#modify-the-package-set

**Comment by thomashoneyman** [comment]
Whoops!

{ “packages”: { “jelly”: “0.7.0” } }

**Comment by thomashoneyman** [comment]
One more try — I’m on mobile and my phone inserted typographic quotes into the JSON there. This is valid JSON:

{
  "packages": {
    "jelly": "0.7.0"
  }
}

**Comment by thomashoneyman** [comment]
@yukikurage looks like the package set doesn’t compile with this change:

https://github.com/purescript/registry/actions/runs/3331701290/jobs/5511745244

**Comment by yukikurage** [comment]
Hmmm, I can build locally ...
I noticed that registry also skipped v0.6.3
I will try to update them in order.

**Comment by yukikurage** [comment]
{
"packages": {
"jelly": "0.6.3"
}
}

**Comment by yukikurage** [comment]
Seems to have worked.
Can I continue to make the package set? Or should I wait to see if registry can successfully publish a package set today?

**Comment by thomashoneyman** [comment]
If jelly was published more than 24 hours ago then it won’t be picked up automatically. You’ll need to submit another update.

**Comment by yukikurage** [comment]
Okay
{
"packages": {
"jelly": "0.7.0"
}
}

**Comment by yukikurage** [comment]
Faild.
In `v0.7.0`, `Jelly.Data.Hooks` does not import `Jelly.Data.Component`, so I don't know what the error message means...

**Comment by thomashoneyman** [comment]
I see. I would guess we are keeping some of the old `jelly@0.6.3` code around in the `output` directory when recompiling the package set and it's a spurious error. I'll take a look as soon as I have a little time.

**Comment by thomashoneyman** [comment]
@yukikurage I have a fix for this and will submit a PR in an hour or two.

**Comment by thomashoneyman** [comment]
Processed in #44
