### ISSUE TITLE
Update node-streams-aff

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/registry#66]
```json
{
  "name": "node-streams-aff",
  "ref": "v4.0.1",
  "compiler": "0.15.4",
  
  "location": {
    "githubOwner": "purescript-node",
    "githubRepo": "purescript-node-streams-aff"
  }
}
```

**Comment by thomashoneyman** [comment]
Hi @jamesdbrock! This isn’t being considered JSON because of the extra space. Resubmitting:

{
  "name": "node-streams-aff",
  "ref": "v4.0.1",
  "compiler": "0.15.4",
  "location": {
    "githubOwner": "purescript-node",
    "githubRepo": "purescript-node-streams-aff"
  }
}

**Comment by thomashoneyman** [comment]
Also I notice the edit — CI only triggers on comments, not edits. Just FYI!
